"""
Curated catalog of destinations and activities for discovery fallback and offline mode.
"""

CURATED_CITIES = [
    {
        "name": "Paris",
        "country": "France",
        "region": "Ile-de-France",
        "latitude": 48.8566,
        "longitude": 2.3522,
        "cost_index": 3.8,
        "popularity": 4.9,
        "image_url": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Tokyo",
        "country": "Japan",
        "region": "Kanto",
        "latitude": 35.6762,
        "longitude": 139.6503,
        "cost_index": 3.6,
        "popularity": 4.95,
        "image_url": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Rome",
        "country": "Italy",
        "region": "Lazio",
        "latitude": 41.9028,
        "longitude": 12.4964,
        "cost_index": 3.2,
        "popularity": 4.8,
        "image_url": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "New York",
        "country": "United States",
        "region": "New York",
        "latitude": 40.7128,
        "longitude": -74.0060,
        "cost_index": 4.5,
        "popularity": 4.9,
        "image_url": "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Barcelona",
        "country": "Spain",
        "region": "Catalonia",
        "latitude": 41.3879,
        "longitude": 2.16992,
        "cost_index": 3.0,
        "popularity": 4.75,
        "image_url": "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Kyoto",
        "country": "Japan",
        "region": "Kansai",
        "latitude": 35.0116,
        "longitude": 135.7681,
        "cost_index": 3.3,
        "popularity": 4.85,
        "image_url": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "London",
        "country": "United Kingdom",
        "region": "Greater London",
        "latitude": 51.5074,
        "longitude": -0.1278,
        "cost_index": 4.2,
        "popularity": 4.88,
        "image_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Sydney",
        "country": "Australia",
        "region": "New South Wales",
        "latitude": -33.8688,
        "longitude": 151.2093,
        "cost_index": 3.9,
        "popularity": 4.7,
        "image_url": "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Amsterdam",
        "country": "Netherlands",
        "region": "North Holland",
        "latitude": 52.3676,
        "longitude": 4.9041,
        "cost_index": 3.7,
        "popularity": 4.65,
        "image_url": "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Cape Town",
        "country": "South Africa",
        "region": "Western Cape",
        "latitude": -33.9249,
        "longitude": 18.4241,
        "cost_index": 2.4,
        "popularity": 4.6,
        "image_url": "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Bangkok",
        "country": "Thailand",
        "region": "Central",
        "latitude": 13.7563,
        "longitude": 100.5018,
        "cost_index": 1.8,
        "popularity": 4.7,
        "image_url": "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
    },
    {
        "name": "Florence",
        "country": "Italy",
        "region": "Tuscany",
        "latitude": 43.7696,
        "longitude": 11.2558,
        "cost_index": 3.1,
        "popularity": 4.7,
        "image_url": "https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&w=800&q=80",
    },
]

CURATED_ACTIVITIES = [
    {
        "city_name": "Paris",
        "name": "Louvre Museum Guided Masterpieces Tour",
        "description": "Explore the world-famous Mona Lisa, Venus de Milo, and iconic wings with priority skip-the-line access.",
        "category": "culture",
        "estimated_cost": 45.00,
        "duration": 150,
        "image_url": "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Paris",
        "name": "Seine River Evening Sunset Cruise & Bistro Dining",
        "description": "Glide past illuminated monuments and bridges while enjoying classic French cuisine.",
        "category": "food",
        "estimated_cost": 65.00,
        "duration": 120,
        "image_url": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Paris",
        "name": "Montmartre Bohemian Artists & Pastry Walking Tour",
        "description": "Stroll cobblestone alleys, visit Sacre-Coeur, and taste fresh artisan croissants and macarons.",
        "category": "culture",
        "estimated_cost": 30.00,
        "duration": 90,
        "image_url": "https://images.unsplash.com/photo-1520939817895-060bdef4df1a?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Tokyo",
        "name": "Tsukiji Outer Market Food & Sushi Tasting Tour",
        "description": "Savor authentic fresh sushi, wagyu skewers, tamagoyaki, and matcha with a local guide.",
        "category": "food",
        "estimated_cost": 50.00,
        "duration": 120,
        "image_url": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Tokyo",
        "name": "teamLab Planets Immersive Digital Art Museum",
        "description": "Walk through water and body-immersive light art installations in Toyosu.",
        "category": "culture",
        "estimated_cost": 35.00,
        "duration": 120,
        "image_url": "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Tokyo",
        "name": "Shibuya & Shinjuku Nightlife Izakaya Crawl",
        "description": "Discover hidden Omoide Yokocho alleys, craft sake, and yakitori bars under glowing neon.",
        "category": "nightlife",
        "estimated_cost": 40.00,
        "duration": 180,
        "image_url": "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Rome",
        "name": "Colosseum, Roman Forum & Palatine Hill Underground",
        "description": "Walk where gladiators stood with an archaeologist guide and express security bypass.",
        "category": "culture",
        "estimated_cost": 55.00,
        "duration": 180,
        "image_url": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Rome",
        "name": "Trastevere Street Food & Traditional Gelato Tour",
        "description": "Sample crispy suppli, artisanal pizza al taglio, roman cheeses, and wine in bohemian Trastevere.",
        "category": "food",
        "estimated_cost": 42.00,
        "duration": 150,
        "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "New York",
        "name": "Central Park Bike Tour & Hidden Trails",
        "description": "Ride through scenic Bethesda Terrace, Strawberry Fields, and the reservoir.",
        "category": "adventure",
        "estimated_cost": 25.00,
        "duration": 120,
        "image_url": "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "New York",
        "name": "Broadway Theatre Evening Experience",
        "description": "Experience world-renowned theatrical performances in the heart of Manhattan's Theater District.",
        "category": "culture",
        "estimated_cost": 110.00,
        "duration": 160,
        "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Barcelona",
        "name": "Sagrada Familia Towers & Antoni Gaudi Masterpieces",
        "description": "Marvel at the extraordinary basilica and climb the Nativity tower for panoramic city views.",
        "category": "culture",
        "estimated_cost": 38.00,
        "duration": 120,
        "image_url": "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Barcelona",
        "name": "Barceloneta Beach Sunset Paddleboarding & Tapas",
        "description": "Relax on the Mediterranean waters followed by sangria and fresh calamari.",
        "category": "relaxation",
        "estimated_cost": 35.00,
        "duration": 90,
        "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Kyoto",
        "name": "Arashiyama Bamboo Grove & Tenryu-ji Zen Garden",
        "description": "Peaceful early morning stroll through soaring bamboo pathways and historic temple gardens.",
        "category": "nature",
        "estimated_cost": 15.00,
        "duration": 100,
        "image_url": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Kyoto",
        "name": "Traditional Matcha Tea Ceremony in Gion",
        "description": "Learn the ancient way of tea preparation with a tea master in a historic machiya townhouse.",
        "category": "culture",
        "estimated_cost": 35.00,
        "duration": 60,
        "image_url": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "London",
        "name": "Tower of London & Crown Jewels Exhibition",
        "description": "Discover centuries of royal intrigue and see the spectacular royal regalia.",
        "category": "culture",
        "estimated_cost": 40.00,
        "duration": 150,
        "image_url": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80",
    },
    {
        "city_name": "Cape Town",
        "name": "Table Mountain Cableway & Summit Nature Hike",
        "description": "Ascend 1000m for sweeping views of the Atlantic Ocean and the Cape Peninsula.",
        "category": "adventure",
        "estimated_cost": 28.00,
        "duration": 180,
        "image_url": "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=600&q=80",
    },
]
