# Generated by Django 6.1 on 2026-08-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flight', 'Flight'), ('lodging', 'Lodging'), ('food', 'Food'), ('transport', 'Transport'), ('activity', 'Activity'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
                ('trip_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.tripstop')),
            ],
            options={
                'db_table': 'expenses_expense',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trip', 'date'], name='expenses_ex_trip_id_2d1c57_idx')],
            },
        ),
    ]
