# Generated by Django 6.1 on 2026-08-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('accommodation', 'Accommodation'), ('activities', 'Activities'), ('meals', 'Meals'), ('other', 'Other'), ('flight', 'Flight'), ('lodging', 'Lodging'), ('food', 'Food'), ('activity', 'Activity'), ('shopping', 'Shopping')], default='other', max_length=50),
        ),
    ]
