# Generated by Django 6.1 on 2026-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
