# Generated by Django 6.1 on 2026-08-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('food', 'Food'), ('culture', 'Culture'), ('nature', 'Nature'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('nightlife', 'Nightlife'), ('other', 'Other')], default='other', max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.PositiveIntegerField(default=60, help_text='Minutes')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.city')),
            ],
            options={
                'db_table': 'activities_activity',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'category'], name='activities__city_id_ef197d_idx')],
            },
        ),
    ]
