# Generated by Django 6.1 on 2026-08-29 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image', models.URLField(blank=True, default='', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_public', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trips_trip',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='destinations.city')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'db_table': 'trips_trip_stop',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_activities', to='activities.activity')),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.tripstop')),
            ],
            options={
                'db_table': 'trips_trip_activity',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'start_date'], name='trips_trip_user_id_03af45_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='trip_stop_date_order_valid'),
        ),
        migrations.AddConstraint(
            model_name='tripactivity',
            constraint=models.UniqueConstraint(fields=('trip_stop', 'activity', 'date'), name='unique_trip_activity_per_day'),
        ),
    ]
